CREATE TABLE USERS
(
    ID            BIGSERIAL PRIMARY KEY,
    USERNAME      VARCHAR NOT NULL UNIQUE,
    HASH_PASSWORD VARCHAR NOT NULL,
    ROLE          VARCHAR NOT NULL DEFAULT 'User',
    STATE         VARCHAR NOT NULL DEFAULT 'Active'
);

CREATE TABLE THEMES
(
    ID    BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR NOT NULL UNIQUE
);

CREATE TABLE POSTS
(
    ID          BIGSERIAL PRIMARY KEY,
    TITLE       VARCHAR NOT NULL UNIQUE,
    DESCRIPTION VARCHAR NOT NULL,
    THEME_ID    BIGINT  NOT NULL REFERENCES THEMES (ID) ON DELETE CASCADE,
    USER_ID     BIGINT  NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE
);